server:
  port: 8082
  context-path: /equipementsSportif
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    password: Pa456lOt
    url: jdbc:mysql://localhost:3306/dbequipementssportifs?useSSL=false&user=root